#pragma once

#define MAX_COLUMNS_PER_TABLE 1024
#define MAX_TABLE_NAME_LEN 128
#define MAX_QUERY_PLAN_DEPTH 64
#define MAX_JOIN_INPUTS 8
#define MAX_LOG_MESSAGE 512

#define RETRY_LIMIT 5
#define PLAN_REOPT_THRESHOLD 0.10
#define GC_EVICT_SCORE_THRESHOLD 0.85
